version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
        php: 8.2
  pre_build:
    commands:
      - echo Running Pre-Build at $(date)
  build:
    on-failure: ABORT
    commands:
      - ls -al
      - add-apt-repository ppa:ondrej/php
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates software-properties-common gpg php8.2 php8.2-gd php8.2-mcrypt php8.2-curl php8.2-intl php8.2-xsl php8.2-mbstring php8.2-zip php8.2-soap php8.2-bcmath php8.2-ctype php8.2-dom php8.2-iconv php8.2-simplexml php8.2-sockets php8.2-cli php8.2-fpm php8.2-xml php8.2-redis php8.2-enchant php8.2-mysql php8.2-cgi php8.2-common php8.2-opcache php8.2-readline php8.2-memcached php8.2-bz2 php-tcpdf unzip wget git aptitude git
      - curl -s https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer install --ignore-platform-req=ext-sodium --optimize-autoloader --prefer-dist --no-dev
      - aws s3 cp s3://mag-pipe-credentials-bucket/env.php app/etc/env.php
artifacts:
    files:
      - '**/*'
    name: mage-deploy.zip
